### ISSUE TITLE
Cannot load pynvim

### ISSUE THREAD

**Issue by waldemarnt** [CopilotC-Nvim/CopilotChat.nvim#101]
Hey! the plugin is not starting and when I check the health I get

```
CopilotChat.nvim health check ~
- OK Python version 3.11 is supported
- OK pynvim version Traceback (most recent call last):
  File "/tmp/lua_4IBJq2.py", line 1, in <module>
  import pynvim; v = pynvim.VERSION; print("{0}.{1}.{2}".format(v.major, v.minor, v.patch))
  ^^^^^^^^^^^^^
  ModuleNotFoundError: No module named 'pynvim' is supported
```

But my python provider looks right

```
Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python in the environment.
- Executable: /usr/local/bin/python
- Python version: 3.9.6
- pynvim version: 0.5.0
- OK Latest pynvim is installed.
```

**specs**:
OSX
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
VimPlug

**Comment by jellydn** [comment]
Hi @waldemarnt Thank you for your report. There are Python versions on your setup. Your Python 3.11 is missing to install dependencies.

What I could suggest:
 - Try to install pip with Python 3.11 instead of 3.9.6
 - Migrate to `canary` which is `lua-based` plugin. Here is my working config github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua 
 
 cc @gptlang @deathbeam

**Comment by waldemarnt** [comment]
> Hi @waldemarnt Thank you for your report. There are Python versions on your setup. Your Python 3.11 is missing to install dependencies.
> 
> What I could suggest:
> 
> * Try to install pip with Python 3.11 instead of 3.9.6
> * Migrate to `canary` which is a `lua-based` plugin. Here is my working config https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua
> 
> cc @gptlang @deathbeam

ah yeah thank you! It's working now, my neovim is using the right version 🚀
