### ISSUE TITLE
feature: enhanced rendering of the chat widow

### ISSUE THREAD

**Issue by folke** [CopilotC-Nvim/CopilotChat.nvim#334]
Are you interested in a PR that allows customizing the chat window like in the screenshot?

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/292349/cf82b4b2-53d9-4cef-aa82-88fd31919083)

**Comment by deathbeam** [comment]
So that basically adds horizontal line after the headers? Imo that looks pretty good yea (was also kinda original intention to just have some sort of horizontal line there but sadly treesitter markdown highlight for `--` horizontal line was kinda just breaking the highlighting, see #239). 

Im assuming it can also be done in nicer way than just iterating through eveything when its part of the plugin instead of it being autocmd.

**Comment by folke** [comment]
That and I'd also allow styling the headers themselves. `CopilotChatQuestionHeader` and `CopilotChatAnswerHeader` linknig by default to `@markup.heading.2.markdown`, so that users/colorschemes can easily style it
