### ISSUE TITLE
Configurability of dependence on `nvim-cmp`

### ISSUE THREAD

**Issue by sereneinserenade** [CopilotC-Nvim/CopilotChat.nvim#429]
I'm using [blink.cmp](https://github.com/Saghen/blink.cmp) and removed `nvim-cmp`(I assume it's looking for `nvim-cmp`, not sure). Below is the error that it gives me when I try to open copilot chat.

Can this be configured to use blink.cmp instead of `nvim-cmp`?

<details open><summary>Error screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/22053d1f-9114-4b5b-876b-d6a4391b00c8)

</p>
</details>

**Comment by timredd** [comment]
I just encountered this - turned out to be an issue with `LazyVim`'s `copilot-chat` extra. The problem is that there's a [fixed call](https://github.com/LazyVim/LazyVim/blob/cb40a09538dc0c417a7ffbbacdbdec90be4a792c/lua/lazyvim/plugins/extras/coding/copilot-chat.lua#L76) to the `cmp` integration in its `setup()` function:
```lua
config = function(_, opts)
    local chat = require("CopilotChat")
    require("CopilotChat.integrations.cmp").setup() -- <- here
    -- ...
end
```

The fix I'm using is to override the `setup` call with my own:
```lua
{
    'CopilotC-Nvim/CopilotChat.nvim',
    config = function(_, opts)
      require('CopilotChat').setup(opts)
    end,
}
```

Since the original `setup` won't run with this tweak, you'll need to copy over anything else that was in there to your own config (if you want to keep it). As of this post, it's only this:
```lua
vim.api.nvim_create_autocmd("BufEnter", {
    pattern = "copilot-chat",
    callback = function()
        vim.opt_local.relativenumber = false
        vim.opt_local.number = false
    end,
})
```

**Comment by deathbeam** [comment]
Looks like lazyvim issue then i guess so not relevant
