### ISSUE TITLE
Code suggestions sometimes contain line numbers

### ISSUE THREAD

**Issue by JockeM** [CopilotC-Nvim/CopilotChat.nvim#570]
Branch: `Canary`
CopilotChat config: [https://gist.github.com/JockeM/c9bfea60cf65ba6e90eb8e331f0b22fb](https://gist.github.com/JockeM/c9bfea60cf65ba6e90eb8e331f0b22fb)

Sometimes, not always I get line numbers in the code suggestions which I have to remove after accepting

Example:
![image](https://github.com/user-attachments/assets/939d1a92-56f6-49e9-b214-633e3fc0f929)

**Comment by deathbeam** [comment]
Yea this can be an issue sometimes. We have to send line numbers prefixed before context because otherwise AI gets confused about line numbers way too often (even when they just start from 0 it gets confused sometimes). And then sometimes the AI gets confused when sending text back and sends back also line numbers.

You can try `claude-3.5-sonnet` instead, with it i saw it happen only like once, its much better at understanding contexts (still sometimes delusional about line numbers so still cant stop sending them). `gpt-4o` is much worse at the line number stuff tho so yea.

**Comment by deathbeam** [comment]
closing this for now as I dont think theres much we can do here, can also move the discussion here i needed

https://github.com/CopilotC-Nvim/CopilotChat.nvim/discussions/420
